apiVersion: v1
kind: Service
metadata: 
   name: demo-svc
   labels: 
   app: nginx
spec: 
  type: NodePort 
  ports: 
    - port: 80 
      nodePort: 30001 
      protocol: TCP 
selector: 
   app: nginx 

