apiVersion: v1
kind: Service
metadata:  
  name: my-loadbal-service
spec:
  selector:    
    app: dev-pod
  type: LoadBalancer
  ports:  
  - name: my-loadbal-port
    port: 80
    targetPort: dev-port
    protocol: TCP
