apiVersion: v1
kind: Pod
metadata:
 name: dev-pod
 labels:
   app: dev-pod
spec:
 containers:
 - name: dev-pod-container
   image: sathyadevops/devops_tom
   ports:
   - name: dev-port
     containerPort: 8080
